### PR TITLE
use ignoreEmptyGroup flag on HitTest

### PR DESCRIPTION
**Pull request by pineapplespatula**
use Core fix for issue https://github.com/adobe-photoshop/spaces-design/issues/1605

### CODE REVIEW

**Comment by chadrolfs** [comment]
@iwehrman would you do the honors of code reviewing and I'll do a functional pass?

**Comment by iwehrman** [comment]
Sorry if this is a dumb question, @pineapplespatula, but is this parameter appropriate for _all_ our `hitTest` use cases?

**Comment by iwehrman** [comment]
It looks like we have ~7 different hit test calls in spaces-design. Are we confident that this is the right change for all of them?

**Comment by pineapplespatula** [comment]
Our Hit test uses are on 

sampler:Click
sampler::doubleClick
SuperSelect:Click 
SuperSelect:DoubleClick 
and SuperSelectOverlay:updateMouseOverHighlights 

I think for all of these cases mousing over the empty potion of a group should not give the user the ability to select that group

**Comment by pineapplespatula** [comment]
So my answer is "Yes" i think it is appropriate.

**Comment by pineapplespatula** [comment]
The only odditiy of selection in sampler is that we do not use the bounds including the FX so if you want to copy the FX you have to click on the layer, and not the FX. This bug is in master though, and is independant of ignoring empty groups. (and I'm going to log it as its own issue)

**Comment by iwehrman** [comment]
Great, thanks.

**Comment by iwehrman** [comment]
@placegraphichere and @jsbache approve of this change. Who am I to argue?

**Pull request merged**
