### PR TITLE
Add a missing options argument to logHeadlightsDataGroup

### PR DESCRIPTION
**Pull request by iwehrman**
The adapter expects an options argument to `_spaces.ps.logHeadlightsDataGroup` which is currently missing. This should fix the problem. I'm a little concerned about the build file though. I ran `grunt build`, but the diff is significantly different. In particular, it does not seem to be minified. I don't think that's actually a problem since the client should perform minification, but there is uncertainty... What do you think, @shaoshing? 

Addresses PS-2566.

### CODE REVIEW

**Comment by shaoshing** [comment]
@iwehrman you can run `webpack --optimize-minimize` get a minimized build. I am not sure why our `webpack.config.js` is not configured to perform this option by default (It can be enabled by appending `new webpack.optimize.UglifyJsPlugin()` to https://github.com/adobe-photoshop/spaces-adapter/blob/master/webpack.config.js#L41). I agree with you on shipping unminized build. I also think it is more useful for development to have the ability to see the original code and full trace info. I remember @volfied opposed the idea thought, so maybe he can explain.

**Comment by shaoshing** [comment]
It is common to publish a ES6 package by compiling each source file into a `lib` folder. 
http://stackoverflow.com/questions/29738381/how-to-publish-a-module-written-in-es6-to-npm

**Comment by iwehrman** [comment]
OK, I ran `webpack --optimize-minimize` to minify the build file and rebased the branch. Please test this before merging!

I am still not convinced that this is the right way to publish this package...

**Comment by shaoshing** [comment]
LGTM!

**Pull request merged**
